### ISSUE TITLE
Update the client to use the Version 3.0 of the bot framework

### ISSUE THREAD

**Issue by zabirauf** [zabirauf/ex_microsoftbot#1]

**Comment by atinder** [comment]
Hi,
Are there any plans for this update ?

**Comment by zabirauf** [comment]
@atinder90 The botV3 branch https://github.com/zabirauf/ex_microsoftbot/tree/botV3 currently contains the changes for the v3 API and also works if you deploy to Heroku or other provider. Lately I haven't gotten chance to do a bit more testing and push it to the master. If you get the change to try the updated API in botV3 branch and find issues then let me know.

**Comment by atinder** [comment]
@zabirauf thanks I am exploring the api.
for wit.ai integration with botV3 we need to update https://github.com/zabirauf/elixir_wit as well right ?

**Comment by zabirauf** [comment]
@atinder90 Nope, the elixir_wit API does not need to be updated as it is completely independent of the Microsoft Bot API.
