### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by Jesterovskiy** [zabirauf/ex_microsoftbot#10]
Can you publish v1.0.0 to Hex? I'll prepare PR to update `phoenix_microsoftbot`

**Comment by zabirauf** [comment]
Thanks @Jesterovskiy for opening the issue. I'll publish v1.0.0 to hex

**Comment by zabirauf** [comment]
@Jesterovskiy Published the 1.0.0 package https://hex.pm/packages/ex_microsoftbot.

I also had to update the tzdata dependency to 0.5.8 as the override was blocking the hex publish. Let me know if you see any issues as I didn't get the chance to test with the updated dependency
