### ISSUE TITLE
Bot Builder SDK v3.5?

### ISSUE THREAD

**Issue by fooqri** [zabirauf/ex_microsoftbot#12]
Is ex_microsoftbot currently compatible with the authentication changes made for botV3.5? Just wondering since the botframework web site claims bots won't work after 07/31/2017 if not compatible.

https://blog.botframework.com/2017/05/07/Bot-Framework-Auth-Change/

https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-authentication

Also, thanks for the very useful module.

**Comment by zabirauf** [comment]
@fooqri The library hasn't been updated to support the changes from botV3.5. Looking at the docs there seems to be few changes but the good thing is that it still is using JWT so I believe the changes involved shouldn't be huge. 
I currently am not able to make the changes but feel free to send a pull request if you make the changes to support it :). Thanks.

**Comment by fooqri** [comment]
Thanks for the response. I will look into it next week. If you have any additional experiences/info/thoughts on what needs to change or gotchas, it might speed the process and would be appreciated.
