### ISSUE TITLE
Incompatible with Elixir 1.3

### ISSUE THREAD

**Issue by xtagon** [zabirauf/ex_microsoftbot#6]
Hi,

Thanks for making this library :+1: 

`ex_microsoftbot 0.1.0` requires `httpotion ~> 2.2`. The problem is, this version of httpotion does not compile on Elixir 1.3. I'm getting this error when I try: https://github.com/myfreeweb/httpotion/issues/90

Would you be able to update the dependency? I'm really just toying around with this library, not depending on it, so it's not a big deal but I though I'd open an issue so you know.

Thanks,
Justin

**Comment by zabirauf** [comment]
@xtagon Thanks! Are you planning to use the library with Microsoft bot framework v1.0 or v3.0. Currently the ex_microsoftbot library which is published only supports v1.0. I am working in [botV3](https://github.com/zabirauf/ex_microsoftbot/tree/botV3) branch to support the v3.0 version. I've already updated the dependency in that branch so that it works with Elixir 1.3. If you indeed plan to use the Microsoft Bot Framework v1.0 then I can update the dependency.

**Comment by xtagon** [comment]
Thanks for the quick response. I'm completely new to Microsoft Bot Framework so I wasn't aware of v1.0 vs. v3.0. As far as I can tell, there is no way for me to choose between versions when registering a new bot, so I'm assuming it would be 3.0.

**Comment by zabirauf** [comment]
Yep, if you are creating a new app then it is set to v3.0 and there is no option to change it to v1.0. I'm working on supporting v3.0, the authentication is nearly done, now dealing with few issues in calling the API. Hopefully should be done in a week. Will update this thread when I publish the new package.

**Comment by xtagon** [comment]
Sounds good, thank you so much! Do you know if the Bot Framework Emulator is meant to emulate v3.0?

**Comment by zabirauf** [comment]
Yep, it supports v3.0

**Comment by zabirauf** [comment]
@xtagon If you wanna play around you can start using the botV3 branch library directly from your elixir project

Change mix.exs to add the dependency

```
{:ex_microsoftbot, github: "zabirauf/ex_microsoftbot", branch: "botV3"},
```

and then add the following in your config

```
config :ex_microsoftbot,
  app_id: System.get_env("APP_ID"),
  app_password: System.get_env("APP_PASSWORD")
```

Either add the app_id & app_password directly or if you are using Heroku then you can get it from system environment variables.

Also check out the echo_phoenix_microsoftbot project (branch botV3) https://github.com/zabirauf/echo_phoenix_microsoftbot/tree/botV3 . You should be able to deploy that on heroku. This is working now, it echos back the message.

I am still testing few things so take a dependency on it for now only if you want to play with it.

**Comment by xtagon** [comment]
I checked out that branch of `echo_phoenix_microsoftbot`. I set my environment variables and tried running it locally (I want to get this working locally before worrying about deployment at all). There is the following error:

```
** (Mix) Could not start application ex_microsoftbot: ExMicrosoftBot.start(:normal, []) returned a bad value: "No auth data defined for ex_microsoftbot."
```

**Comment by zabirauf** [comment]
If you want to run locally then i would suggest that add the following to `dev.exs`

```
config :ex_microsoftbot,
  app_id: "YOUR_APP_ID",
  app_password: "YOUR_APP_PASSWORD"
```

Dont take a dependency on System.get_env in case of local testing, directly putting strings is easier. If you don't want to put clear credentials in those config files then taking a dependency on environment variable should work. Can you run `iex` after setting those env vars and see if `System.get_env("APP_ID")` works.

**Comment by xtagon** [comment]
If I run `iex` then `System.get_env("APP_ID")` and `System.get_env("APP_PASSWORD")` show the correct values. However, if I run `iex -S mix` or `mix phoenix.server` with the same environment variables, there is an error.

In fact, even if I hard code the values into the config instead of using `System.get_env`, I still get the error when I try to run it. Strange.

**Comment by zabirauf** [comment]
Are you editing **prod.exs** or **dev.exs**? You should add those values to **dev.exs** as when you run locally that config is used. 
If you want to run as prod environment run `MIX_ENV=prod iex -S mix`

**Comment by xtagon** [comment]
Thank you, how silly of me! I was editing prod.exs :laughing: 

I put them in dev.exs now. Here's what happens when I `mix phoenix.start`

```
mix phoenix.server
[debug] RefreshableAgent.get_refreshed_state_and_schedule_refresh/2 -> nil
[debug] deserialize_response/2: Error response: closed
[debug] deserialize_response/2: Error response: %HTTPotion.ErrorResponse{message: "closed"}

=INFO REPORT==== 15-Aug-2016::21:22:36 ===
    application: logger
    exited: stopped
    type: temporary

=INFO REPORT==== 15-Aug-2016::21:22:36 ===
    application: cowboy
    exited: stopped
    type: temporary

=INFO REPORT==== 15-Aug-2016::21:22:36 ===
    application: cowlib
    exited: stopped
    type: temporary

=INFO REPORT==== 15-Aug-2016::21:22:36 ===
    application: ranch
    exited: stopped
    type: temporary
** (Mix) Could not start application ex_microsoftbot: ExMicrosoftBot.start(:normal, []) returned an error: shutdown: failed to start child: ExMicrosoftBot.TokenManager
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, 0, "closed"}
            (ex_microsoftbot) lib/token_manager.ex:73: ExMicrosoftBot.TokenManager.refresh_token/1
            (ex_microsoftbot) lib/token_manager.ex:35: ExMicrosoftBot.TokenManager.get_refreshed_state/2
            (ex_microsoftbot) lib/refreshable_agent.ex:76: ExMicrosoftBot.TokenManager.get_refreshed_state_and_schedule_refresh/2
            (ex_microsoftbot) lib/refreshable_agent.ex:30: ExMicrosoftBot.TokenManager.init/1
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

This looks to me like it's trying to get the token from Microsoft Bot Engine. Of course since I'm running locally, I need it to use my BFE emulator. I started the emulator before hand, and made sure the endpoint was correct (left at the default) and the app ID and password were correct. Still no luck.

I'll give it another try some other time. Thank you for helping me so far!

**Comment by zabirauf** [comment]
Ohh, you are trying with emulator, currently the support for emulator is not complete. Its something next on my list. It does work with the Microsoft bot framework though.

**Comment by ghost** [comment]
I'm trying to run it too and I get the same error than xtagon. Here is the configuration file.

`config :ex_microsoftbot,
  app_id: "e144...",
  app_password: "Ez...",
  endpoint: "http://localhost:9000",
  openid_valid_keys_url: "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration",
  issuer_claim: "https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/",
  audience_claim: "https://graph.microsoft.com",
  using_bot_emulator: false,
  disable_token_validation: false`

I'm not able to start the phoenix server. 

How can I make it work so I can test directly on the Microsoft dashboard ?

Thanks

**Comment by ghost** [comment]
Needed to add 
config :ssl, protocol_version: :"tlsv1.2"
in config/config.exs

**Comment by zabirauf** [comment]
@Ghost0226 Seems like an issue with OTP 19 https://github.com/edgurgel/httpoison/issues/130 . I didn't get the error because i am running on OTP 18 due to another issue with HTTPotion.
